---
title: "Callan's Budget 2021"
author: Callan Hoskins
date: "`r Sys.Date()`"
output: 
  github_document:
    toc: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning=FALSE, message=FALSE)
```

```{r message=FALSE, warning=FALSE}
# Packages
library(tidyverse)
library(lubridate)

# Parameters
spreadsheet <- "./data/Chase1821_Activity20220101_20220812_20220812.CSV"
#===============================================================================

# Code
amounts <- 
  read_csv(spreadsheet) %>% 
  transmute(
    transaction_date = parse_date(`Transaction Date`, "%m/%d/%Y"), 
    amount = Amount, 
    desc = Description, 
    category = Category
  )

budget <- 
  tribble(
    ~category, ~yearly, 
    "Home", 1e3, 
    "Gifts", 2e3, 
    "Food", 5.7e3, 
    "Transportation", 2e3, 
    "Charity", 1e3, 
    "Rent", 21.6e3, 
    "Savings", 5e3, 
    "Investments", 20e3, 
    "General", 11.4e3, 
    "Utilities", 2520, 
    "Travel", 3.6e3, 
    "Healthcare", 1e3, 
    "Taxes", 43e3
  ) %>% 
  mutate(weekly = yearly / 52, monthly = yearly / 12)
```

```{r}
amounts <- 
  amounts %>% 
  mutate(
    weekday = transaction_date %>% wday(label = TRUE, abbr = FALSE), 
    week = transaction_date - (wday(transaction_date)), 
    month = transaction_date %>% month(label = TRUE, abbr = FALSE)
  )
```



```{r}
first_date <- 
  amounts %>% 
  pull(transaction_date) %>% 
  min()

last_date <- 
  amounts %>% 
  pull(transaction_date) %>% 
  max()

weeks_elapsed <- as.double(difftime(last_date, first_date, units = "weeks"))

amounts %>% 
  group_by(category) %>% 
  summarize(spending = sum(amount)) %>% 
  transmute(category, weekly = spending / weeks_elapsed, amount = "Spent") %>% 
  bind_rows(
    budget %>% transmute(category, weekly, amount = "Budget")
  ) %>% 
  mutate(spent_str = scales::dollar_format(largest_with_cents = 0)(weekly)) %>% 
  ggplot(aes(category, weekly, label = spent_str, fill = amount)) + 
  geom_col(position = "dodge") + 
  geom_text() + 
  scale_y_continuous(labels=scales::dollar_format()) + 
  scale_fill_manual(values = c("#2D7B17", "#EE1300")) + 
  labs(
    x = NULL, 
    y = "Weekly Spending", 
    fill = NULL, 
    title = "Average Weekly Spending This Year"
  ) + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```


```{r}
yearly_budget <- 
  budget %>% 
  pull(yearly) %>% 
  sum()

yearly_spent <- 
  amounts %>% 
  pull(amount) %>% 
  sum()

deficit <- (yearly_budget * weeks_elapsed / 52) - yearly_spent
```

Your yearly deficit so far is $`r deficit`, or `r deficit / (yearly_budget * weeks_elapsed / 52)`%.  

```{r}
amounts %>% 
  group_by(category) %>% 
  summarize(spending = sum(amount)) %>% 
  right_join(budget, by = "category") %>% 
  replace(is.na(.), 0) %>% 
  mutate(spending = spending / yearly) %>% 
  ggplot(aes(category, spending)) + 
  geom_col(fill = "#BA65A3") + 
  geom_abline(intercept = weeks_elapsed / 52, slope = 0, color = "red") + 
  geom_abline(intercept = 1, slope = 0) + 
  scale_y_continuous(labels = scales::label_percent()) + 
  labs(
    x = NULL, 
    y = "Yearly spending (% of budget)", 
    fill = NULL, 
    title = "Budget Progress (%)"
  ) + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```

```{r}
monthh <- "March"
last_month <- amounts %>% filter(month == monthh)
last_month %>% 
  group_by(category) %>% 
  summarize(spending = sum(amount)) %>% 
  transmute(category, monthly = spending, amount = "Spent") %>% 
  bind_rows(
    budget %>% transmute(category, monthly, amount = "Budget")
  ) %>% 
  mutate(spent_str = scales::dollar_format(largest_with_cents = 0)(monthly)) %>% 
  ggplot(aes(category, monthly, label = spent_str, fill = amount)) + 
  geom_col(position = "dodge") + 
  geom_text() + 
  scale_y_continuous(labels=scales::dollar_format()) + 
  scale_fill_manual(values = c("#2D7B17", "#EE1300")) + 
  labs(
    x = NULL, 
    y = "Spent", 
    fill = NULL, 
    title = str_c(monthh, " Spending")
  ) + 
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```
```{r}
amounts %>% 
  mutate(mon = 
           transaction_date %>% 
           floor_date(unit = "month") %>% 
           as.Date(format(mon, "%d-%m-%Y"), format = "%d-%m-%Y")
  ) %>% 
  group_by(mon, category) %>% 
  summarize(spending = sum(amount)) %>% 
  mutate(mon = as.Date(format(mon, "%d-%m-%Y"), format = "%d-%m-%Y")) %>% 
  ggplot(aes(mon, spending, color = category)) + 
  geom_line() +
  geom_point() + 
  coord_cartesian(ylim = c(0, 3e3)) + 
  scale_x_date(labels = scales::date_format("%b %Y")) + 
  scale_y_continuous(labels=scales::dollar_format()) + 
  scale_color_brewer(palette = "Paired") + 
  labs(
    title = "Spending by Category Over Time", 
    color = NULL, 
    x = "Month",
    y = "Spent"
  )
```
```{r}
s <- sum(amounts %>% pull(amount))
amounts %>% 
  group_by(category) %>% 
  summarize(spending = sum(amount)) %>% 
  arrange(desc(category)) %>% 
  mutate(prop = spending / s * 100) %>% 
  mutate(
    ypos = cumsum(prop) - 0.5 * prop, 
    category = str_c(category, " \n($", floor(spending), ")")
  ) %>% 
  ggplot(aes(x = "", y = prop, fill = category)) + 
  geom_bar(stat = "identity", width = 1, color = "white") + 
  ggrepel::geom_label_repel(
    aes(y = ypos, label = category), 
    color = "white", 
    size = 3
  ) + 
  coord_polar("y", start = 0) + 
  labs(title = "Proportion of Spending by Category", fill = NULL) + 
  theme_void() + 
  theme(legend.position = "none")
```


